<?php

/**
 * Implements hook_page_attachments().
 */
function toast_messages_page_attachments(array &$attachments) {
  // add condition to load the selected library
  $attachments['#attached']['library'][] = 'toast_messages/toastr';

  $attachments['#attached']['library'][] = 'toast_messages/toast_messages';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function toast_messages_preprocess_html(&$variables) {

  $settings = \Drupal::config('toast_messages.settings');
  $current_user_roles = \Drupal::currentUser()->getRoles();
  if (
    !(
      $settings->get('disableForAdmin') &&
      in_array('administrator', $current_user_roles)
    )
  ) {
    $messenger = \Drupal::messenger();
    $messages = $messenger->all();
    if (!empty($messages)) {
      $messenger->deleteAll();
      $variables['#attached']['drupalSettings']['toast_messages'] = [
        'messages' => $messages,
        'options' => $settings->getRawData(),
      ];
    }
  }
}
